CREATE TABLE CUSTOMERS(
   ID   INT              NOT NULL,
   NAME VARCHAR (20)     NOT NULL,
   AGE  INT              NOT NULL,
   ADDRESS  CHAR (25) ,
   SALARY   DECIMAL (18, 2),       
   PRIMARY KEY (ID)
);/* CREATING A TABLE */

DESC CUSTOMERS;/* CHECKING THE STRUCTURE OF THE TABLE */

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (1, 'Ramesh', 32, 'Ahmedabad', 2000.00 );   

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (2, 'Khilan', 25, 'Delhi', 1500.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (3, 'kaushik', 23, 'Kota', 2000.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (4, 'Chaitali', 25, 'Mumbai', 6500.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (5, 'Hardik', 27, 'Bhopal', 8500.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (6, 'Komal', 22, 'MP', 4500.00 );

INSERT INTO CUSTOMERS
VALUES (7, 'Muffy', 24, 'Indore', 10000.00 );/* INSERTING DATA IN THE TABLE */

SELECT * FROM CUSTOMERS;/* SELECT STATEMENT */

SELECT ID, NAME, SALARY 
FROM CUSTOMERS
WHERE SALARY > 2000;/* SELECT STATEMENT */

SELECT ID, NAME, SALARY 
FROM CUSTOMERS
WHERE NAME = 'Hardik';

SELECT ID, NAME, SALARY 
FROM CUSTOMERS
WHERE SALARY > 2000 AND age < 25;/* AND OPERATION */

SELECT ID, NAME, SALARY 
FROM CUSTOMERS
WHERE SALARY > 2000 OR age < 25;/* OR STATEMENT */

SELECT * FROM CUSTOMERS
WHERE SALARY LIKE '200%';/* LIKE STATEMENT */

SELECT * FROM CUSTOMERS
   ORDER BY NAME, SALARY;/* ORDER BY QUERY */
   
SELECT NAME, SUM(SALARY) FROM CUSTOMERS
GROUP BY NAME;/* GROUP BY QUERY */

SELECT DISTINCT SALARY FROM CUSTOMERS
   ORDER BY SALARY;/* DISTINCT KEYWORD */

CREATE TABLE ORDERS(
   OID   INT              NOT NULL,
   DATE  VARCHAR (20)     NOT NULL,
   CUSTOMER_ID  INT              NOT NULL,
   AMOUNT   INT (25)      NOT NULL,       
   PRIMARY KEY (OID)
);
INSERT INTO ORDERS (OID,DATE,CUSTOMER_ID,AMOUNT)
VALUES (102, '2009-10-08 00:00:00',3,3000  );

INSERT INTO ORDERS (OID,DATE,CUSTOMER_ID,AMOUNT)
VALUES (100, '2009-10-08 00:00:00',3,1500  );

INSERT INTO ORDERS (OID,DATE,CUSTOMER_ID,AMOUNT)
VALUES (101, '2009-11-20 00:00:00',2,1560  );

INSERT INTO ORDERS (OID,DATE,CUSTOMER_ID,AMOUNT)
VALUES (103, '2008-05-20 00:00:00 ',4,2060  );

SELECT* FROM ORDERS;

SELECT ID, NAME, AGE, AMOUNT
   FROM CUSTOMERS, ORDERS
   WHERE  CUSTOMERS.ID = ORDERS.CUSTOMER_ID;/* JOIN STATEMENT*/
   
 SELECT  ID, NAME, AMOUNT, DATE
   FROM CUSTOMERS
   LEFT JOIN ORDERS
   ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID;/*LEFT JOIN*/
 
   SELECT  ID, NAME, AMOUNT, DATE
   FROM CUSTOMERS
   RIGHT JOIN ORDERS
   ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID;/*RIGHT JOIN*/
   
   SELECT  ID, NAME, AMOUNT, DATE
   FROM CUSTOMERS
   LEFT JOIN ORDERS
   ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID
UNION
   SELECT  ID, NAME, AMOUNT, DATE
   FROM CUSTOMERS
   RIGHT JOIN ORDERS
   ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID;/*UNION CLAUSE*/
   
   SELECT  a.ID, b.NAME, a.SALARY
   FROM CUSTOMERS a, CUSTOMERS b
   WHERE a.SALARY < b.SALARY;/*SELF JOIN */
   
   SELECT  ID, NAME, AMOUNT, DATE
   FROM CUSTOMERS, ORDERS;/*CARTESIAN JOIN*/
   
   SELECT  ID, NAME, AGE, ADDRESS, SALARY
   FROM CUSTOMERS
   WHERE SALARY IS NOT NULL;/*NOT NULL*/
   
   SELECT C.ID, C.NAME, C.AGE, O.AMOUNT 
   FROM CUSTOMERS AS C, ORDERS AS O
   WHERE  C.ID = O.CUSTOMER_ID;/* ALIAS */
   
   CREATE VIEW CUSTOMERS_VIEW AS
SELECT name, age
FROM  CUSTOMERS;

SELECT * FROM CUSTOMERS_VIEW;/*VIEWS */

 SELECT ID, NAME, AGE, ADDRESS, SALARY
FROM CUSTOMERS
GROUP BY age
HAVING COUNT(age) >= 2;/*HAVING CLAUSE*/

DELETE FROM CUSTOMERS
   WHERE AGE = 25;
   COMMIT;/* COMMIT*/
   
   ROLLBACK;/*ROLLBACK*/
 SELECT * FROM CUSTOMERS
WHERE SALARY LIKE '200%';

